namespace: "prod"

cronjob:
  image:
    repositoryPrefix: "058264142001.dkr.ecr.eu-south-1.amazonaws.com"
    imagePullPolicy: Always
    tag: $IMAGE_TAG_PLACEHOLDER
    digest: $IMAGE_DIGEST_PLACEHOLDER
  resources:
    requests:
      cpu: "1"
      memory: "2Gi" # CHECK-THIS!
    limits:
      cpu: "1"
      memory: "2Gi" # CHECK-THIS!
