name: K8s Diff (sub)

on: 
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run diff against'
        required: true
        type: string
    secrets:
      AWS_REGION:
        required: true
      EKS_CLUSTER_NAME:
        required: true

defaults:
  run:
    shell: bash

env:
  SCRIPTS_FOLDER: "./interop-infra-commons/scripts/helm"

jobs:
  workflow_setup:
    name: Setup steps
    runs-on: [ self-hosted, "run_id:${{ inputs.environment }}-${{ github.run_id }}" ]
    environment: ${{ inputs.environment }}
    env:
      TARGET_ENVIRONMENT: ${{ inputs.environment }}
    outputs:
      microservices: ${{ steps.set-outputs.outputs.microservices }}
      cronjobs: ${{ steps.set-outputs.outputs.cronjobs }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - id: set-outputs
        run: |
          echo "microservices=$(find microservices -type f -path "*/$TARGET_ENVIRONMENT/values.yaml" -exec dirname {} \; | awk -F'/' '{print $2}' | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
          echo "cronjobs=$(find jobs -type f -path "*/$TARGET_ENVIRONMENT/values.yaml" -exec dirname {} \; | awk -F'/' '{print $2}' | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  diff_microservices:
    name: ${{ matrix.microservice }}
    needs: [ workflow_setup ]
    runs-on: [self-hosted, "run_id:${{ inputs.environment }}-${{ github.run_id }}"]
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        microservice: ${{ fromJson(needs.workflow_setup.outputs.microservices) }}
      fail-fast: false
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Checkout scripts repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        with:
          repository: pagopa/interop-infra-commons
          path: interop-infra-commons 
          fetch-depth: 0
          sparse-checkout: 'scripts/helm'
          token: ${{ secrets.PRIVATE_REPOS_PAT }}
          ref: ${{ vars.INFRA_COMMONS_TAG }}

      - name: Set kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
      - name: Helm Chart Template
        id: helm_template
        env: 
          MICROSERVICE_NAME: ${{ matrix.microservice }}
        run: |
          set -euo pipefail
          
          export PROJECT_DIR=$(pwd)
          $SCRIPTS_FOLDER/helmTemplate-svc-single.sh --debug --environment ${{ inputs.environment }} --microservice $MICROSERVICE_NAME --output console
      - name: Kubectl Diff
        id: kubectl_diff
        env: 
          MICROSERVICE_NAME: ${{ matrix.microservice }}
        run: |
          set -euo pipefail

          set +e
          export PROJECT_DIR=$(pwd)
          $SCRIPTS_FOLDER/kubectlDiff-svc-single-standalone.sh --environment ${{ inputs.environment }} --microservice $MICROSERVICE_NAME --output console
          DIFF_EXIT_CODE=$?
          set -e
          
          if [[ $DIFF_EXIT_CODE == 0 ]]; then
            echo "Diff Output: No diff has been found for ${MICROSERVICE_NAME}"
          elif [[ $DIFF_EXIT_CODE == 1 ]]; then
            echo "Diff Output: Diff has been found for ${MICROSERVICE_NAME}"
            
            touch microservices_${MICROSERVICE_NAME}_diff.txt
            echo $MICROSERVICE_NAME >> microservices_${MICROSERVICE_NAME}_diff.txt
            echo "diff=true" >> $GITHUB_OUTPUT
          else
            echo "::error title=Diff Error::Error occurred during diff, exit code $DIFF_EXIT_CODE"
            exit $DIFF_EXIT_CODE
          fi
      - name: Upload artifact
        if: ${{ steps.kubectl_diff.outputs.diff }}
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with:
          name: microservices_${{ matrix.microservice }}_diff
          path: microservices_${{ matrix.microservice }}_diff.txt
          retention-days: 1

  diff_cronjobs:
    name: ${{ matrix.cronjob }}
    needs: [ workflow_setup ]
    runs-on: [ self-hosted, "run_id:${{ inputs.environment }}-${{ github.run_id }}" ]
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        cronjob: ${{ fromJson(needs.workflow_setup.outputs.cronjobs) }}
      fail-fast: false
    steps:    
      - name: Checkout
        id: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Checkout scripts repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        with:
          repository: pagopa/interop-infra-commons
          path: interop-infra-commons 
          fetch-depth: 0
          sparse-checkout: 'scripts/helm'
          token: ${{ secrets.PRIVATE_REPOS_PAT }}
          ref: ${{ vars.INFRA_COMMONS_TAG }}
      - name: Set kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
      - name: Helm Chart Template
        id: helm_template
        env: 
          CRONJOB_NAME: ${{ matrix.cronjob }}
        run: |
          set -euo pipefail
          
          export PROJECT_DIR=$(pwd)
          $SCRIPTS_FOLDER/helmTemplate-cron-single.sh --debug --environment ${{ inputs.environment }} --job $CRONJOB_NAME --output console
      - name: Kubectl Diff
        id: kubectl_diff
        env: 
          CRONJOB_NAME: ${{ matrix.cronjob }}
        run: |
          set -euo pipefail

          set +e
          export PROJECT_DIR=$(pwd)
          $SCRIPTS_FOLDER/kubectlDiff-cron-single-standalone.sh --environment ${{ inputs.environment }} --job $CRONJOB_NAME --output console
          DIFF_EXIT_CODE=$?
          set -e
          
          if [[ $DIFF_EXIT_CODE == 0 ]]; then
            echo "Diff Output: No diff has been found for ${CRONJOB_NAME}"
          elif [[ $DIFF_EXIT_CODE == 1 ]]; then
            echo "Diff Output: Diff has been found for ${CRONJOB_NAME}"
            
            touch cronjobs_${CRONJOB_NAME}_diff.txt
            echo $CRONJOB_NAME >> cronjobs_${CRONJOB_NAME}_diff.txt
            echo "diff=true" >> $GITHUB_OUTPUT
          else
            echo "::error title=Diff Error::Error occurred during diff, exit code $DIFF_EXIT_CODE"
            exit $DIFF_EXIT_CODE
          fi
      - name: Upload artifact
        if: ${{ steps.kubectl_diff.outputs.diff }}
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with:
          name: cronjobs_${{ matrix.cronjob }}_diff.txt
          path: cronjobs_${{ matrix.cronjob }}_diff.txt
          retention-days: 1

  print_summary:
    name: Print Diff Summary
    if: ${{ always() }}
    needs: [ workflow_setup, diff_microservices, diff_cronjobs ]
    runs-on: [ self-hosted, "run_id:${{ inputs.environment }}-${{ github.run_id }}" ]
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Download microservices diff artifact
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
        with:
          path: diff-artifacts
          merge-multiple: true
      - name: Print summary
        run: |
          set -euo pipefail
          
          if [ -d diff-artifacts ]; then

            microservices=$(ls -R diff-artifacts | { grep -i "microservice" || :; }| sed 's/_diff.txt//g' | sed 's/microservices_//g' |  tr "\n" ",")
            cronjobs=$(ls -R diff-artifacts | { grep -i "cronjob" || :; } | sed 's/_diff.txt//g' | sed 's/cronjobs_//g' | tr "\n" ",")

            
            echo "### K8s Diff Summary" >> $GITHUB_STEP_SUMMARY
            
            if [ -n "$microservices" ]; then
              IFS=',' read -r -a MICROSERVICES_WITH_DIFF <<< "$microservices"
              if [ -n "$MICROSERVICES_WITH_DIFF" ]; then
              echo "#### Microservices:" >> $GITHUB_STEP_SUMMARY
              fi

              for item in ${MICROSERVICES_WITH_DIFF[@]}; do
              echo "- $item" >> $GITHUB_STEP_SUMMARY
              done
            fi
            
            if [ -n "$cronjobs" ]; then
              IFS=',' read -r -a CRONJOBS_WITH_DIFF <<< "$cronjobs"
              if [ -n "$CRONJOBS_WITH_DIFF" ]; then
                echo "#### Cronjobs:" >> $GITHUB_STEP_SUMMARY
              fi          
              for item in ${CRONJOBS_WITH_DIFF[@]}; do
                echo "- $item" >> $GITHUB_STEP_SUMMARY
              done
            fi

          else
            echo "No diff found" >> $GITHUB_STEP_SUMMARY
          fi

